version: '3.8'
services:
  backend:
    build:
      context: ./backend/web4
    ports:
      - "8080:8080"
    volumes:
      - ./backend/web4:/app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
#      - SPRING_DATA_REDIS_HOST=redis
#      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/web4
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: web4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  redis:
#    image: "redis:latest"
#    hostname: redis
#    ports:
#      - "6379:6379"

volumes:
  db_data: