spring:
  application:
    name: web4

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/web4
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: simple

  data:
    jdbc:
      dialect: postgresql

jwt:
  secret: wpembytrwcvnryxksdbqwjebruyGHyudqgwveytrtrCSnwifoesarjbwe
  header: Authorization

server:
  port: 8080